receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # OTLP
  #otlp:
    #endpoint: otelcol:4317
  # Data sources: traces
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
      #exporters: [spanmetrics, otlp]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    #metrics:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [logging, otlp, prometheus]
    #metrics/spanmetrics:
    #    receivers: [spanmetrics]
    #    exporters: [prometheus]
  